language: php

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: TYPO3_VERSION=^8.7
    - php: 7.1
      env: TYPO3_VERSION=^8.7

sudo: false

before_script:
  - composer require typo3/cms="$TYPO3_VERSION"

script:
  - vendor/bin/phpunit --color=always --coverage-clover=coverage.xml
  - vendor/bin/phpcs -n --standard=PSR2 --extensions=php tests/ src/

after_success:
    - bash <(curl -s https://codecov.io/bash)